
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trener1db
    username: trener1
    password: haslo1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true

